### ISSUE TITLE
Add score always gets a Failure with Error "Parameters Invalid or Unset"

### ISSUE THREAD

**Issue by realDLPS** [freezernick/ue-gjapi-core#114]
Previously working blueprints suddenly stopped working and multiple projects have the same error even with a clean install of the plugin.

Previous packaged version of a game still functions but the project no longer works in editor

Still a big thanks to you for making this plugin as all other features seem to work correctly :)

**Comment by realDLPS** [comment]
Blueprints started working again for no reason that I can figure out, because of course when I open an issue it fixes itself. I am so sorry for wasting your time, have a good rest of the weekend

**Comment by freezernick** [comment]
No worries, you haven't wasted my time in any way
