### ISSUE TITLE
Packaging Issue

### ISSUE THREAD

**Issue by gejatogames** [freezernick/ue-gjapi-core#191]
I am using Unreal Engine 5.4 and whenever I try to package my project, I get the error, "Expecting to find a type to be declared in a module rules named 'GameJoltAPI' in 'UE5Rules, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.  This type must derive from the 'ModuleRules' type defined by UnrealBuildTool.". I'm not exactly sure why this error is showing. Thank you.

**Comment by freezernick** [comment]
I'll look into this and keep you updated.

Thanks for the report!

**Comment by freezernick** [comment]
I haven't yet been able to reproduce this and I need more information.

1. Are you trying to package a C++ or a Blueprint Project?
2. Have you downloaded the plugin from GameJolt or from GitHub?
3. Where did you install the plugin? In the project's plugin directory or the engine directory?
4. Which packaging options are you using?

**Comment by gejatogames** [comment]
1. Blueprint project
2. From Game Jolt
3. In the engine directory
4. In the project files I changed my Build Configuration to Shipping and enabled Full Rebuild, and then I click on Platforms and Package Project for Windows

**Comment by freezernick** [comment]
Hi @gejatogames ,

I could finally reproduce this error by moving the plugin folder around.
Please make sure that the plugin is installed into

`Engine\Plugins\Marketplace\GameJoltAPI`

Please reopen the issue when the error persists
