### ISSUE TITLE
Plugin side error

### ISSUE THREAD

**Issue by Desoxyno** [freezernick/ue-gjapi-core#192]
Hi! I recently used the UE5 GameJolt API, and in my blueprints, I did this :

![Capture d'écran 2024-10-24 110553](https://github.com/user-attachments/assets/b9f72383-7c36-4215-abc9-dc4df2863026)
![Capture d'écran 2024-10-24 110618](https://github.com/user-attachments/assets/3c7390d9-d30e-434c-bb02-eb87043c0650)

Everything works fine when the custom event activates. However, when the reward trophy appears, I get the error "An unknown error on the plugin's side has occured"
Don't worry, I removed the game's private key to keep it secure.

**Comment by freezernick** [comment]
Thanks for the report, I'll take a look ASAP

**Comment by Desoxyno** [comment]
Thank you so much, I've been working on this issue for two days now

**Comment by freezernick** [comment]
I couldn't reproduce the exact behaviour until now, but you can safely remove the "Initialize"-Node before the "Reward Trophy"-Node. "Initialize" must not be called more than once in the game's lifecycle.

**Comment by Desoxyno** [comment]
Thank you so much, but now I have another issue—it's showing 'credentials invalid'
![Capture d'écran 2024-10-24 190423](https://github.com/user-attachments/assets/2995c955-6900-46e5-af92-1e3ccb8e523e)
![Capture d'écran 2024-10-24 190400](https://github.com/user-attachments/assets/c89fff90-e7c9-4615-9694-3671411f43a4)
![Capture d'écran 2024-10-24 190410](https://github.com/user-attachments/assets/d9ae093f-73e6-499a-861a-5d3cdbe7e6f3)

**Comment by Desoxyno** [comment]
Sorry, finally i figured out the solution by myself, thank you

**Comment by freezernick** [comment]
I'm happy to hear that! If you have any other questions regarding the plugin's usage, feel free to join the Discord community

https://dc.freezernick.de
