### ISSUE TITLE
Error Unreal 4.25.4

### ISSUE THREAD

**Issue by chuky025** [freezernick/ue-gjapi-core#70]
I downloaded Unreal 4.25 to test older versions of the plugin and it keeps failing to compile, I'm starting to think it's my problem and not the plugin. xd

VERSIONS:
v2 - Release Candidate 3 (4.25)
Output log: https://paste.ubuntu.com/p/FFPvpZVy5z/

v1 - 4.25
Output log: https://paste.ubuntu.com/p/j8qnCd9WGg/

**Comment by freezernick** [comment]
In this case it's an error of the plugin, because the 4.25-RC3 version on GameJolt is an outdated build. I will upload a fixed RC3 build and ping you here so you can test it again in 4.25. If it then works fine, we can know for sure that it's something with the 4.26 or your project.

**Comment by freezernick** [comment]
I've already tested it with my 4.25.4 and it is the same issue as #69 (nice). So I' will close this in favour of the mentioned issue
